#! /usr/bin/env sh

ALIAS_use_torsocks="torsocks"

#
ALIAS_browser_gui="uzbl"

#
ALIAS_browser_text="lynx"

#
ALIAS_browser_stdout="mdget"

#
ALIAS_browser_links_stdout="linkget"

#
ALIAS_gocryptfs_password_store="$HOME/.config/gocryptfs_password"

#

# debootstrap opts preset
export devuan_debootstrap_opts="--keyring /usr/share/keyrings/devuan-keyring.gpg"

# emit and trim a the web address of a github repository
github_weburl(){
    FINAL_URL=$(git remote -v | grep origin | head -n 1 | sed 's|origin||' | sed 's|(fetch)||' | sed 's|git@|https://|' | tr -d '\t' | tr -d " " | sed 's|\.git||')
    echo "$FINAL_URL"
}

# Defaults for surfraw
sr(){
    export SURFRAW_graphical_browser="$ALIAS_browser_gui"
    export SURFRAW_graphical=yes
    export proxy_url="$TOR_PROXY"
    echo "sr          $@ &
    $SURFRAW_graphical_browser
    "
    "$TORSOCKS" /usr/bin/surfraw $@ &
}
surfraw(){
    sr $@
}

# Defaults for skinnydip
dip(){
    export GPM_user_bin_browser="$ALIAS_browser_gui"
    export GPM_user_bin_cookies="$HOME/.local/share/uzbl/cookies.txt"
    export proxy_url="$TOR_PROXY"
    echo "dip $@ &
    $GPM_user_bin_browser
    "
    "$TORSOCKS" /usr/bin/skinnydip $@ &
}
skinnydip(){
    dip $@
}

#   override the google elvi from surfraw. Shorten the duckduckgo elvi for
# convenience.
alias google="duckduckgo"
alias ddg="duckduckgo"

#   override the default aliases for surfraw.
alias sr="sr "
alias surfraw="sr "

#   override the default aliases for skinnydip.
alias dip="dip "
alias skinnydip="dip "

#   add a command for directly listing the surfraw elvi since we'll be playing
# with the outputs.
alias elvi="/usr/bin/surfraw -elvi"
alias wapp="/usr/bin/skinnydip -wapp"

#   set up cd so it will accept aliases for the paths.
alias cd='cd '
