#! /usr/bin/env sh

export ALIAS_use_torsocks="torsocks"
export TORSOCKS="torsocks"
#
export ALIAS_browser_gui="uzbl-core"

#
export ALIAS_browser_text="lynx"

#
export ALIAS_browser_stdout="mdget"

#
export ALIAS_browser_links_stdout="linkget"

#
export ALIAS_gocryptfs_password_store="$HOME/.config/gocryptfs_password"

#

# debootstrap opts preset
export devuan_debootstrap_opts="--keyring /usr/share/keyrings/devuan-keyring.gpg"

# emit and trim a the web address of a github repository
github_weburl(){
    FINAL_URL=$(git remote -v | grep origin | head -n 1 | sed 's|origin||' | sed 's|(fetch)||' | tr ':' '/'| sed 's|git@|https://|g' | tr -d '\t' | tr -d " " | sed 's|\.git||g' | sed 's|https//||g')
    echo "$FINAL_URL"
}

# Defaults for surfraw
sr(){
    echo "surfraw"
    export SURFRAW_graphical_browser="$ALIAS_browser_gui"
    echo "$SURFRAW_graphical_browser"
    export SURFRAW_graphical=yes
    echo "$SURFRAW_graphical"
    echo "sr          $@ &
    $SURFRAW_graphical_browser
    "
    $TORSOCKS /usr/bin/surfraw $@ &
}
surfraw(){
    sr $@
}

# Defaults for skinnydip
dip(){
    echo "skinnydip"
    export GPM_user_bin_browser="$ALIAS_browser_gui"
    echo "$GPM_user_bin_browser"
    export GPM_user_bin_cookies="$HOME/.local/share/uzbl/cookies.txt"
    echo "$GPM_user_bin_cookies"
    echo "dip $@ &
    $GPM_user_bin_browser
    "
    $TORSOCKS /usr/bin/skinnydip $@ &
}
skinnydip(){
    dip $@
}

#   override the google elvi from surfraw. Shorten the duckduckgo elvi for
# convenience.
alias google="duckduckgo"
alias ddg="duckduckgo"

#   add a command for directly listing the surfraw elvi since we'll be playing
# with the outputs.
alias elvi="/usr/bin/surfraw -elvi"
alias wapp="/usr/bin/skinnydip -wapp"

#   set up cd so it will accept aliases for the paths.
alias cd='cd '
