#! /bin/sh
DLNA_SHARED_AUDIOBOOK="$HOME/Audio/Books/"
DLNA_SHARED_AUDIOPLAYS="$HOME/Audio/Theatre/"
DLNA_SHARED_COMEDY="$HOME/Audio/Comedy/"
DLNA_SHARED_MUSIC="$HOME/Audio/Music/"
DLNA_SHARED_ROCK="$HOME/Audio/Music/Rock/"
DLNA_SHARED_RAP="$HOME/Audio/Music/Rap/"
DLNA_SHARED_ALTERNATIVE="$HOME/Audio/Music/Alternative/"
DLNA_SHARED_CLASSIC="$HOME/Audio/Music/Classical/"
DLNA_SHARED_JAZZ="$HOME/Audio/Music/Jazz/"
DLNA_SHARED_BLUES="$HOME/Audio/Music/Blues/"
DLNA_SHARED_DLNA_SHARED_MOVIES="$HOME/Video/Movies/"
DLNA_SHARED_TV="$HOME/Video/Television/"
DLNA_SHARED_PRESENTATION="$HOME/Video/Presentations/"
DLNA_SHARED_CLASSES="$HOME/Video/Classes/"
music(){
	nohup youtube-dl -v  \
                --prefer-free-formats \
		--output "$DLNA_SHARED_MUSIC/%(creator)s.%(uploader)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
musicplaylist(){
	nohup youtube-dl -v  \
                --prefer-free-formats \
		--output "$DLNA_SHARED_MUSIC/%(playlist)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
audiodrama(){
        nohup youtube-dl -v  \
                --prefer-free-formats \
		--output "$DLNA_SHARED_AUDIOPLAYS/%(creator)s.%(uploader)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
audiodramaplaylist(){
        nohup youtube-dl -v  \
                --prefer-free-formats \
		--output "$DLNA_SHARED_AUDIOPLAYS/%(playlist)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
audionews(){
        nohup youtube-dl -v  \
                --prefer-free-formats \
		--output "$DLNA_SHARED_NEWS/%(creator)s.%(uploader)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
audionewsplaylist(){
        nohup youtube-dl -v  \
                --prefer-free-formats \
		--output "$DLNA_SHARED_NEWS/%(playlist)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
audiobook(){
        nohup youtube-dl -v  \
                --prefer-free-formats \
		--output "$DLNA_SHARED_AUDIOBOOK/%(creator)s.%(uploader)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
audiobookplaylist(){
        nohup youtube-dl -v  \
                --prefer-free-formats \
		--output "$DLNA_SHARED_AUDIOBOOK/Downloads/AudioBook/%(playlist)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
audiocomedy(){
        nohup youtube-dl -v  \
                --prefer-free-formats \
		--output "$DLNA_SHARED_COMEDY/%(creator)s.%(uploader)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
audiocomedyplaylist(){
        nohup youtube-dl -v  \
                --prefer-free-formats \
		--output "$DLNA_SHARED_COMEDY/%(playlist)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
movie(){
	nohup youtube-dl -v  \
		--prefer-free-formats \
		--output "$DLNA_SHARED_MOVIES/%(creator)s.%(uploader)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
movieplaylist(){
	nohup youtube-dl -v  \
		--prefer-free-formats \
		--output "$DLNA_SHARED_MOVIES/%(playlist)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
DLNA_SHARED_TV="$HOME/Downloads/TVShows"
show(){
	nohup youtube-dl -v  \
		--prefer-free-formats \
		--output "$DLNA_SHARED_TV/%(creator)s.%(uploader)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
showplaylist(){
	nohup youtube-dl -v  \
		--prefer-free-formats \
		--output "$DLNA_SHARED_TV/%(playlist)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
DLNA_SHARED_PRESENTATION="$HOME/Downloads/Presentations"
presentation(){
	nohup youtube-dl -v  \
		--prefer-free-formats \
		--output "$DLNA_SHARED_PRESENTATION/%(creator)s.%(uploader)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
presentationplaylist(){
	nohup youtube-dl -v  \
		--prefer-free-formats \
		--output "$DLNA_SHARED_PRESENTATION/%(playlist)s/%(title)s.%(ext)s" \
		"$1" >~/Downloads/youtube-dl.log 2>&1 &
	bash -c 'sleep 3; cat ~/Downloads/youtube-dl.log' &
	echo "ydllog to view log"
}
ydllog(){
	tail -f "$HOME/Downloads/youtube-dl.log"
}
setup_links(){
        mkdir -p ~/Audio
        mkdir -p ~/Video
        mkdir -p "$DLNA_SHARED_AUDIOBOOK"
        mkdir -p "$DLNA_SHARED_AUDIOPLAYS"
        mkdir -p "$DLNA_SHARED_COMEDY"
        mkdir -p "$DLNA_SHARED_MUSIC"
        mkdir -p "$DLNA_SHARED_ROCK"
        mkdir -p "$DLNA_SHARED_RAP"
        mkdir -p "$DLNA_SHARED_ALTERNATIVE"
        mkdir -p "$DLNA_SHARED_CLASSIC"
        mkdir -p "$DLNA_SHARED_JAZZ"
        mkdir -p "$DLNA_SHARED_BLUES"
        mkdir -p "$DLNA_SHARED_MOVIES"
        mkdir -p "$DLNA_SHARED_TV"
        mkdir -p "$DLNA_SHARED_PRESENTATION"
        mkdir -p "$DLNA_SHARED_CLASSES"

        ln -s "$DLNA_SHARED_MUSIC" "$HOME/Music/Downloaded"
        ln -s "$DLNA_SHARED_AUDIOPLAYS" "$HOME/Audio/Plays"
        ln -s "$DLNA_SHARED_TV" "$HOME/Videos/TV"
        ln -s "$DLNA_SHARED_MOVIES" "$HOME/Videos/Movies"
        ln -s "$DLNA_SHARED_CLASSES" "$HOME/Videos/Classes"
        ln -s "$DLNA_SHARED_PRESENTATION" "$HOME/Videos/Presentations"
}
alias song=music
alias song=musicplaylist
alias radrama=audiodrama
alias radramapl=audiodramaplaylist
alias news=audionews
alias newspl=audionewspl
alias book=audiobook
alias bookpl=audiobookplaylist
alias standup=audiocomedy
alias standuppl=audiocomedyplaylist
alias film=movie
alias filmpl=movieplaylist
alias tv=show
alias tvpl=showpl
alias conv=presentation
alias convpl=presentationplaylist
alias ylog=ydllog
