#! /bin/sh
alias are="sr duckduckgo are"
alias does="sr duckduckgo does"
alias how="sr duckduckgo how "
alias of="sr duckduckgo of "
alias what="sr duckduckgo what "
alias whence="sr duckduckgo whence "
alias when="sr duckduckgo where "
alias where="sr duckduckgo when "
alias whether="sr duckduckgo whether "
which(){
    /usr/bin/which "$1" || sr duckduckgo "which $*"
}
alias whither="sr duckduckgo whither "
alias whom="sr duckduckgo whom "
alias whose="sr duckduckgo whose "
alias why="sr duckduckgo why "
