#! /usr/bin/env sh
alias wicd="wicd-curses"
alias pcmanfm="nohup pcmanfm . >/dev/null 2>&1 &"
alias dateset="sudo date --set \"\$(curl -s --head https://google.com | grep ^Date: | sed 's/Date: //g')\""

meditor(){
	medit_open_files=""
	if [ -f "Makefile" ]; then
		medit_open_files="Makefile"
	fi
    if [ -f "Dockerfile" ]; then
		medit_open_files="$medit_open_files Dockerfile"
	fi
    if [ -f "INSTALL" ]; then
		medit_open_files="$medit_open_files INSTALL"
	fi
	if [ -f "README.md" ]; then
		medit_open_files="$medit_open_files README.md"
    fi
	if [ -f "README" ]; then
		medit_open_files="$medit_open_files README"
	fi
    if [ -f "auto/config" ]; then
		medit_open_files="$medit_open_files auto/config"
	fi
    if [ -f "build.sh" ]; then
		medit_open_files="$medit_open_files build.sh"
	fi
	nohup medit --new-app --use-session=no ${medit_open_files} "$@" >/dev/null 2>&1 &
}
alias medit="meditor "

finder(){
        find "$@" 2> /dev/null
}
alias find="finder "

tox(){
	cd "$HOME/Tox" || exit
	ratox ./tox.save
}
alias ratox=tox

myip(){
	curl http://checkip.dyndns.com/ | sed "s@$TRIM_STR_BEGIN@@" | sed "s@$TRIM_STR_END@@"
}

alias term="nohup stterms >/dev/null 2>&1 &"
alias acs="apt-cache search"
alias acv="apt-cache show"


