#! /usr/bin/env sh
alias safe="gocryptfs -passfile /media/ENCRYPTED/SafeKombination \$HOME/Sync/.Safe \$HOME/unSafe"
alias unsafe="fusermount -u \$HOME/unSafe"
alias usbsafe="sudo cryptsetup -d \$HOME/.USBPASS luksOpen /dev/sdb1 LUKSUSB"
alias usbunsafe="sudo cryptsetup luksClose LUKSUSB"
signcrypt(){
	gpg -se -u "$MY_KEY" -r "$1" "$2"
}
sign(){
	gpg --clear-sign -u "$MY_KEY" "$1"
}
selfcrypt(){
	gpg -se -u "$MY_KEY" -r "$MY_KEY" "$1"
}
signpkmnt(){
	gpg --batch --yes --clear-sign -u "$SIGNING_KEY" "$1"
}
