#! /usr/bin/env sh
alias wicd="nohup wicd-gtk &>/dev/null &"
alias pcmanfm="nohup pcmanfm . &> /dev/null &"
meditor(){
	DEFAULT_FILE=""
	if [ -f "Makefile" ]; then
		DEFAULT_FILE="Makefile"
	fi
	if [ -f "README.md" ]; then
		DEFAULT_FILE="$DEFAULT_FILE README.md"
	elif [ -f "README" ]; then
		DEFAULT_FILE="$DEFAULT_FILE README"
	fi
        if [ -f "auto/config" ]; then
		DEFAULT_FILE="$DEFAULT_FILE auto/config"
	fi
        if [ -f "build.sh" ]; then
		DEFAULT_FILE="$DEFAULT_FILE build.sh"
	fi
	nohup medit --new-app --use-session=no $DEFAULT_FILE "$@" &> /dev/null &
}
alias medit="meditor "
alias hangouts="docker run -it --rm --name hangups --volumes-from hangups-session tdryer/hangups"
alias dateset="sudo date --set \"$(curl -s --head http://google.com | grep ^Date: | sed 's/Date: //g')\""
tox(){
	cd "$HOME/Tox"
	ratox ./tox.save
}
alias ratox=tox
alias logtail="tail -n 100 log"
alias errtail="tail -n 100 err"
export DEBOOTSTRAPOPTS="--keyring /usr/share/keyrings/devuan-keyring.gpg"
web(){
	nohup sr W "$@" &> /dev/null &
}
alias edalias="medit ~/$HOME/.bash_*aliases*"
alias dub="nohup sakura &> /dev/null &"
repopush(){
        export DEV_MESSAGE="$@"
        make push
}
alias make-push=repopush
alias apt-get=apt
alias acs="apt-cache search"
