#! /bin/sh

DLNA_SHARED_AUDIOBOOK="$HOME/Audio/Books/"
DLNA_SHARED_AUDIOPLAYS="$HOME/Audio/Theatre/"
DLNA_SHARED_COMEDY="$HOME/Audio/Comedy/"
DLNA_SHARED_AUDIONEWS="$HOME/Audio/News/"
DLNA_SHARED_MUSIC="$HOME/Audio/Music/"
DLNA_SHARED_ROCK="$HOME/Audio/Music/Rock/"
DLNA_SHARED_RAP="$HOME/Audio/Music/Rap/"
DLNA_SHARED_ALTERNATIVE="$HOME/Audio/Music/Alternative/"
DLNA_SHARED_CLASSIC="$HOME/Audio/Music/Classical/"
DLNA_SHARED_JAZZ="$HOME/Audio/Music/Jazz/"
DLNA_SHARED_BLUES="$HOME/Audio/Music/Blues/"
DLNA_SHARED_MOVIES="$HOME/Video/Movies/"
DLNA_SHARED_TV="$HOME/Video/Television/"
DLNA_SHARED_PRESENTATION="$HOME/Video/Presentations/"
DLNA_SHARED_CLASSES="$HOME/Video/Classes/"

youtube_dl_warning(){
echo "DLNA Auto-Add Aliases Enabled:
=============================="

    echo "
This system has been configured to automatically organize content that is
downloaded from streaming video sites. If you are sure you want to use
youtube-dl directly, please invoke it using the full path, $(which youtube-dl)"

    echo "
## spoken word aliases  | folder:

   * audiobook          |   $DLNA_SHARED_AUDIOBOOK
   * audiodrama         |   $DLNA_SHARED_AUDIOPLAYS
   * audiocomedy        |   $DLNA_SHARED_COMEDY
   * audionews          |   $DLNA_SHARED_AUDIONEWS

## music aliases        | folder:

   * music              |   $DLNA_SHARED_MUSIC
   * rock               |   $DLNA_SHARED_ROCK
   * rap                |   $DLNA_SHARED_RAP
   * alternative        |   $DLNA_SHARED_ALTERNATIVE
   * classic            |   $DLNA_SHARED_CLASSIC
   * jazz               |   $DLNA_SHARED_JAZZ
   * blues              |   $DLNA_SHARED_BLUES

## video aliases        | folder:

   * movie              |   $DLNA_SHARED_MOVIES
   * tv                 |   $DLNA_SHARED_TV
   * presentation       |   $DLNA_SHARED_PRESENTATION
   * class              |   $DLNA_SHARED_CLASSES
    "
}

alias youtube-dl=youtube_dl_warning

alias audiobooks="$DLNA_SHARED_AUDIOBOOK"
alias audiodrama="$DLNA_SHARED_AUDIOPLAYS"
alias audiocomedy="$DLNA_SHARED_COMEDY"
alias audionews="$DLNA_SHARED_AUDIONEWS"
alias music="$DLNA_SHARED_MUSIC"
alias rock="$DLNA_SHARED_ROCK"
alias rap="$DLNA_SHARED_RAP"
alias alternative="$DLNA_SHARED_ALTERNATIVE"
alias classic="$DLNA_SHARED_CLASSIC"
alias jazz="$DLNA_SHARED_JAZZ"
alias blues="$DLNA_SHARED_BLUES"
alias movies="$DLNA_SHARED_MOVIES"
alias tv="$DLNA_SHARED_TV"
alias presentation="$DLNA_SHARED_PRESENTATION"
alias classes="$DLNA_SHARED_CLASSES"

music(){
    cd "$DLNA_SHARED_MUSIC" || exit
    yget $@
}
#musicplaylist(){

#}
rock(){
    cd "$DLNA_SHARED_ROCK" || exit
    yget $@
}
#rockplaylist(){

#}
rap(){
    cd "$DLNA_SHARED_RAP" || exit
    yget $@
}
#rapplaylist(){

#}
alternative(){
    cd "$DLNA_SHARED_ALTERNATIVE" || exit
    yget $@
}
#alternativeplaylist(){

#}
classic(){
    cd "$DLNA_SHARED_CLASSIC" || exit
    yget $@
}
#classicplaylist(){

#}
jazz(){
    cd "$DLNA_SHARED_JAZZ" || exit
    yget $@
}
#jazzplaylist(){

#}
blues(){
    cd "$DLNA_SHARED_BLUES" || exit
    yget $@
}
#bluesplaylist(){

#}
audiodrama(){
    cd "$DLNA_SHARED_AUDIOPLAYS" || exit
    yget $@
}
#audiodramaplaylist(){

#}
audionews(){
    cd "$DLNA_SHARED_AUDIONEWS" || exit
    yget $@
}
#audionewsplaylist(){

#}
audiobook(){
    cd "$DLNA_SHARED_AUDIOBOOK" || exit
    yget $@
}
#audiobookplaylist(){

#}
audiocomedy(){
    cd "$DLNA_SHARED_COMEDY" || exit
    yget $@
}
#audiocomedyplaylist(){

#}
movie(){
    cd "$DLNA_SHARED_MOVIES" || exit
    yget $@
}
#movieplaylist(){

#}
tv(){
    cd "$DLNA_SHARED_TV" || exit
    yget $@
}
#showplaylist(){

#}
presentation(){
    cd "$DLNA_SHARED_PRESENTATION" || exit
    yget $@
}
#presentationplaylist(){

#}
class(){
    cd "$DLNA_SHARED_CLASSES" || exit
    yget $@
}
#classplaylist(){

#}
setup_links(){
        mkdir -p ~/Audio
        mkdir -p ~/Video
        mkdir -p "$DLNA_SHARED_AUDIOBOOK"
        mkdir -p "$DLNA_SHARED_AUDIOPLAYS"
        mkdir -p "$DLNA_SHARED_COMEDY"
        mkdir -p "$DLNA_SHARED_AUDIONEWS"
        mkdir -p "$DLNA_SHARED_MUSIC"
        mkdir -p "$DLNA_SHARED_ROCK"
        mkdir -p "$DLNA_SHARED_RAP"
        mkdir -p "$DLNA_SHARED_ALTERNATIVE"
        mkdir -p "$DLNA_SHARED_CLASSIC"
        mkdir -p "$DLNA_SHARED_JAZZ"
        mkdir -p "$DLNA_SHARED_BLUES"
        mkdir -p "$DLNA_SHARED_MOVIES"
        mkdir -p "$DLNA_SHARED_TV"
        mkdir -p "$DLNA_SHARED_PRESENTATION"
        mkdir -p "$DLNA_SHARED_CLASSES"
}
