#! /usr/bin/env sh
alias docker_aptcacher="docker run --name apt-cacher-ng -d --restart=always   --publish 3142:3142   --volume /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng   sameersbn/apt-cacher-ng:latest"
alias hangups="docker pull tdryer/hangups ; docker run -it --rm --name hangups --volumes-from hangups-session tdryer/hangups"
