#! /usr/bin/env sh
surfr(){
        nohup sr "$@" >/dev/null 2>&1 &
}
alias ddg="duckduckgo"
alias sr="surfr "
agithub(){
        retdir=$(pwd)
        if [ -d "$retdir/.git" ]; then
                if git remote -v | grep origin | head -n 1 | grep github ; then
                        FINAL_URL=$(git remote -v | grep origin | head -n 1 | sed 's|origin||' | sed 's|(fetch)||' | tr ":" "/" | sed 's|git@|https://|' | tr -d '\t' | tr -d " " | sed 's|\.git||')
                        echo "$FINAL_URL"
                        cd ~ && nohup sr W "$FINAL_URL" >/dev/null 2>&1 & cd "$retdir" || exit 1
                fi
        else
                cd ~/ && nohup sr github "$@" >/dev/null 2>&1 & cd "$retdir" || exit 1
        fi
}
alias github="agithub "
alias voice="nohup sr W https://voice.google.com/ >/dev/null 2>&1 &"
alias openmailbox="nohup sr W https://openmailbox.org/ >/dev/null 2>&1 &"
alias valadoc="nohup sr W https://valadoc.org >/dev/null 2>&1 &"
alias godoc="nohup sr W https://godoc.org >/dev/null 2>&1 &"
sreddit(){
        nohup sr W https://reddit.com/r/"$1" >/dev/null 2>&1 &
}
alias subreddit="sreddit "
alias reddit="sreddit "
