#! /usr/bin/env sh

#   Plain-text code repository search: Dump a list of links from a github search
# with non-repo URL's removed
cr(){
    export SURFRAW_text_browser="linkget"
    temp="$SURFRAW_graphical"
	SURFRAW_graphical=no
    "$TORSOCKS"	/usr/bin/surfraw github -type=repo "$@" \
        | grep -v -s 'https://github.com/opensearch.xml' \
        | grep -v -s 'https://github.com/site' \
        | grep -v -s 'https://github.com/privacy' \
        | grep -v -s 'https://github.com/security' \
        | grep -v -s 'https://github.com/articles' \
        | grep -v -s 'https://github.com/about' \
        | grep -v -s 'https://github.com/contact' \
        | grep -v -s 'https://github.com/blog' \
        | grep -v -s 'https://github.com/login' \
        | grep -v -s 'https://github.com/join' \
        | grep -v -s 'https://github.com/business' \
        | grep -v -s 'https://github.com/topics' \
        | grep -v -s 'https://github.com/feature' \
        | grep -v -s 'https://github.com/explore' \
        | grep -v -s 'https://github.com/marketplace' \
        | grep -v -s 'https://github.com/pricing' \
        | grep -v -s 'https://status.github.com/' \
        | grep -v -s 'https://help.github.com/' \
        | grep -v -s 'https://developer.github.com/' \
        | grep -v -s 'https://training.github.com/' \
        | grep -v -s 'https://shop.github.com/' \
        | grep -v -s 'https://github.com/search' \
        | grep -v -s 'https://twitter.com/' \
        | grep -v -s 'stargazers' \
        | grep -v -s '.css' \
        | grep -v -s 'References'
    SURFRAW_graphical="$temp"
}

#   Automatically launch a gui browser directly to a github repository's web
# interface
github(){
        retdir=$(pwd)
        if [ -d "$retdir/.git" ]; then
                if git remote -v | grep origin | head -n 1 | grep github ; then
                        FINAL_URL=github_weburl
                        echo "$FINAL_URL"
                        cd ~ && \
                            sr W "$FINAL_URL" >/dev/null 2>&1 & \
                        cd "$retdir" || exit 1
                fi
        else
                cd ~ && \
                    sr github "$@" >/dev/null 2>&1 & \
                cd "$retdir" || exit 1
        fi
}

alias github="github "


alias voice="nohup sr W https://voice.google.com/ >/dev/null 2>&1 &"
alias openmailbox="nohup sr W https://openmailbox.org/ >/dev/null 2>&1 &"
alias valadoc="nohup sr W https://valadoc.org >/dev/null 2>&1 &"
alias godoc="nohup sr W https://godoc.org >/dev/null 2>&1 &"
sreddit(){
        nohup sr W https://reddit.com/r/"$1" >/dev/null 2>&1 &
}
alias subreddit="sreddit "
alias reddit="sreddit "
alias syncweb="sr W 127.0.0.1:5833"
