#! /usr/bin/env sh

check_conky(){
    pgrep conky | wc -l
}

run_once(){
    pgrep "$@" > /dev/null || ("$@" &)
}

unset_display(){
    unset "$1"
    UNSET_TEST=$(eval "echo \$$1")
    echo "testing unset $1 $UNSET_TEST"
}

send_text(){
    /usr/bin/curl http://textbelt.com/text -d "number=$1" -d "message=$2"
}

overwrite(){
    dd if=/dev/urandom of="$HOME/overwrite"
    \rm "$HOME/overwrite"
}

cleancache(){
	rm -rfv "$HOME/.cache" &
	rm -rfv "$HOME/.xombreronion/cookies.txt" &
	rm -rfv "$HOME/.xombreronion/sessions" &
	rm -rfv "$HOME/.xombreronion/tmp" &
        rm -rfv "$HOME/.xombreronion/cache" &
	history -c
}

alias tunset=unset_display

alias rm="srm -z"

alias sms=send_text

alias ssh="$TORSOCKS ssh"

alias chckcnky=check_conky
alias cnkystrt=conky_start
alias cnkystp=conky_stop
alias cnkyrstrt=conky_restart

alias dir="\ls --color=auto"
