#! /usr/bin/env sh
#This file contains aliases useful for working with i2p and i2pd
i2p_name(){
	sudo -u i2pd cat /var/lib/i2pd/addressbook/addresses.csv | grep "$1"
}
alias i2pns="i2p_name"
alias i2pdlog="sudo -u i2pd tail -f /var/log/i2pd.log"
